# Generated by Django 5.0.3 on 2024-04-04 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='Supplies_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='配件分类')),
            ],
            options={
                'verbose_name': '配件种类',
                'verbose_name_plural': '配件种类',
            },
        ),
        migrations.CreateModel(
            name='SuppliesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='配件名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='配件描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplies/%Y/%m/%d/', verbose_name='配件图片')),
                ('number', models.IntegerField(default=0, verbose_name='库存数量')),
            ],
            options={
                'verbose_name': '配件信息',
                'verbose_name_plural': '配件信息',
            },
        ),
    ]
