# Generated by Django 5.0.3 on 2024-04-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplies', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies_category',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brandinfo', verbose_name='适用品牌'),
        ),
        migrations.AddField(
            model_name='supplies_category',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='suppliesinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.supplies_category', verbose_name='配件种类'),
        ),
        migrations.AddField(
            model_name='suppliesinfo',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.variantinfo', verbose_name='车型'),
        ),
    ]
