# Generated by Django 5.0.3 on 2024-04-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_alter_supplies_category_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliesinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价'),
        ),
    ]
