# Generated by Django 5.0.3 on 2024-04-04 15:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='品牌')),
            ],
            options={
                'verbose_name': '品牌信息',
                'verbose_name_plural': '品牌信息',
            },
        ),
        migrations.CreateModel(
            name='Product_Year_Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('year', models.CharField(max_length=4, verbose_name='年份')),
                ('month', models.CharField(default=1, max_length=2, verbose_name='月份')),
            ],
            options={
                'verbose_name': '生产年月',
                'verbose_name_plural': '生产年月',
            },
        ),
        migrations.CreateModel(
            name='VariantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='车型')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brandinfo', verbose_name='品牌')),
                ('product_Year_Month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.product_year_month', verbose_name='生产年月')),
            ],
            options={
                'verbose_name': '车型信息',
                'verbose_name_plural': '车型信息',
            },
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='车辆名称')),
                ('VIN', models.CharField(max_length=20, verbose_name='车架号')),
                ('color', models.CharField(max_length=20, verbose_name='颜色')),
                ('image', models.ImageField(default='/VehicleDefaultImg.jpg', upload_to='vehicles/%Y/%m/%d/', verbose_name='车辆照片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.variantinfo')),
            ],
            options={
                'verbose_name': '车辆信息',
                'verbose_name_plural': '车辆信息',
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=200, verbose_name='消息')),
                ('has_read', models.BooleanField(default=False, verbose_name='已读状态')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicleinfo', verbose_name='车辆')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
